version: '3'
services:

  hazelcast:
    image: hazelcast/hazelcast
    volumes:
    - ~/hazelcast/resources:/configFolder
    environment:
    - JAVA_OPTS=-Dhazelcast.config=/configFolder/hazelcast.xml -Dhazelcast.mancenter.url=http://mancenter:8080/hazelcast-mancenter -Dgroup.name=osif -Dgroup.password=osif-pass
    ports:
    - 5701:5701
    links:
    - "management-center:mancenter"

  management-center:
    image: hazelcast/management-center
    volumes:
    - ~/hazelcast/mancenter3.8:/mancenter-3.8
    environment:
    - MANCENTER_DATA=/mancenter-3.8
    - JAVA_OPTS=-Dhazelcast.mc.rest.enabled=true
    ports:
    - 8088:8080
